[package]
name = "malb8dge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.1.5"
itertools = "0.10.5"
rand = "0.8.5"
regex = "1.6"
yansi = "0.5.1"